### PR TITLE
Settings page

### PR DESCRIPTION
**Pull request by JonDerThan**
Implementation of a settings page to change the search parameters of the injected links #2. In addition to the parameters used by Anna's Archive, the author's name can now be added to the search query #12.

Additionally a large refactor was done. Most notably, the different files for the add-on and the userscript were coalesced into one file. The script now decides at runtime whether it can use the `browser` API (only supported for add-ons).

### CODE REVIEW

**Comment by arogl** [comment]
For the userscript, do we need to modify the script, which will then not enable updates?

I did not see a setting in Tampermonkey to configure the script.

**Comment by JonDerThan** [comment]
Yes, the idea is to modify the script, I've supplied some example settings at the top of the script. I didn't intend to publish this as a userscript originally (I didn't even know about them before somebody asked about it), so I didn't put that much thought into it. I also didn't find a built-in method to create a settings page for userscripts. Apparently there's a way to [store data permanently in userscripts](https://stackoverflow.com/a/76165095) but it has different APIs for different userscript managers.

I also don't have any data about how many people are even using this project as a userscript; I'm not even sure why you don't use the add-on instead. Is it because you're using Chrome instead of Firefox?

**Comment by arogl** [comment]
Yes, I am on chrome.

I'll try downloading the XPI, unzip and load unpacked extension

**Comment by arogl** [comment]
It works, 2 errors. 

If you feel like looking into a chrome extension, here are the errors.

The first is Firefox specific reference
image


The second, I am not sure about.
image

**Comment by JonDerThan** [comment]
Sorry for the late response, I didn't have that much time the past few days.

I was hesitant to publish the add-on in the Chrome store at first because I didn't know whether an add-on like this would be allowed on there and I didn't expect many people to use the add-on anyways. I'll try to publish it on there, I've already created an account for it (it costs $5 to register for whatever reason). I'll let you know if they accept the add-on.

Thanks for the tests! Annoyingly, I recently switched the manifest back to v2 (8d2febd) because apparently Firefox for Android doesn't support content scripts in manifest v3 ([issue I created on Stackoverflow regarding this](https://stackoverflow.com/questions/77753827/manifest-v3-content-scripts-not-running-on-firefox-on-android)). I'll create another manifest for Chrome, that will eliminate the first two warnings.

The third, `browser is not defined` error is because Chrome names their API `chrome`, while Firefox uses the more neutral sounding `browser` API. The functionality however is the same (at least regarding the features I'm using), which is why Firefox accepts both, I'll just replace the few occurences of the API.

**Comment by JonDerThan** [comment]
@arogl, the add-on is now available in the Chrome webstore! :)

Somehow it doesn't pop up when I search for it in the store, but there's a link for it in the readme.

**Pull request merged**
